### Upload a .mat File
POST http://localhost:8080/api/hsi/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Dioni.mat"
Content-Type: application/octet-stream

< C:\Development\dataset\HyperspectralImage\dataset1\HyRANK\Dioni.mat
--WebAppBoundary--

### 2. Download/Serve the File (using RequestParam)
GET http://localhost:8080/api/upload?filename=WHU_Hi_HongHu.mat
Accept: application/octet-stream