spring.application.name=Server

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB

# Todo: Need modification in production env
app.upload.location=C:/Development/repositories/HSI-SYSTEM/SharedData/uploads